### ISSUE TITLE
Authorship and license

### ISSUE THREAD

**Issue by peschuster** [baltedewit/hyperdeck-server-connection#1]
Hey @baltedewit,

stating from the amout of identical code my casparcg-hyperdeck project seemed to have been an inspiration for this library.

It is always nice to see derivative work, but usual etiquette is to state the source of copied code or concepts, to recognize the (indirect) contributon of other people's time and work.

Also there is no license statement in my own repository. Technically this means that the code is not "open source" and not licensed for copying and modifications. Although this is not my intention and I just have not decided on a license, yet; already re-licensing the code fragments as MIT is probably in the "darker grey" area. But I don't mind that. It is just something I noticed.

Don't get me wrong. I think it is great work. I was just suprised by the "familiarity" of the code without finding any note about the source and would appreciate if you could rectify this.

**Comment by baltedewit** [comment]
Hi,

Yes, there should have been a statement about that in the readme from the beginning! I'm sorry about that. I sometimes get excited by the engineering so much that I forget the important details. If it makes you feel any better to know, I didn't omit it on purpose. I also wasn't aware there was still so much identical code around, I figured an enum here or there perhaps but otherwise I had rewritten server, socket and parser classes completely. Had I known there was much identical code around I would have probably reconsidered publishing at all.

Beyond the general mention of your project in the readme, how do you feel this would be resolved correctly? One thing that comes to my mind is to, for now, relicense this repo to unlicensed as well, although I am not sure if that is much more than a symbolical gesture since I am not a licensing expert.

**Comment by baltedewit** [comment]
I have updated the readme file regarding acknowledgements. FYI, your package.json says the project is under MIT license so you should perhaps change that if it's not true.

**Comment by peschuster** [comment]
I just added the MIT license to the project, so the license thing should be resolved. As already said, it was not a real issue for me, but just something "incorrect".

At the end it is all about the gesture. Leaving a note about things others contributed does not cost anything and inspires for more sharing and open source contributions. I don't expect you to overdo it. When there is nothing left from the orginal source this note might also be go away...

So that is all good for me. Discovering this in combination with the license thing was just a little bit to much for me to not mention it.

Keep up the good work 👍

**Comment by baltedewit** [comment]
> Discovering this in combination with the license thing was just a little bit to much for me to not mention it.

And rightly so.

> Keep up the good work

And you!
